# 문제정의
두 행렬을 곱하는 문제

# 알고리즘 설명
쉬트라쎈 알고리즘을 사용 -> 7개의 행렬을 구해 이들이 구해지면, 원래의 행렬 곱셈을 구한다.

# 손으로 푼 예제

In [2]:
#알고리즘 코드
import numpy as np

def strassen(A,B):
    n=len(A)
    if n==1:
        return A*B
    
    n2=n//2
    A11,A12,A21,A22=A[:n2,:n2],A[:n2,n2:],A[n2:,:n2],A[n2:,n2:]
    B11,B12,B21,B22=B[:n2,:n2],B[:n2,n2:],B[n2:,:n2],B[n2:,n2:]

    M1=strassen(A11+A22,B11+B22)
    M2=strassen(A21+A22,B11)
    M3=strassen(A11,B12-B22)
    M4=strassen(A22,B21-B11)
    M5=strassen(A11+A12,B22)
    M6=strassen(A21-A11,B11+B12)
    M7=strassen(A12-A22,B21+B22)

    C11=M1+M4-M5+M7
    C12=M3+M5
    C21=M2+M4
    C22=M1+M3-M2+M6

    C=np.vstack((np.hstack((C11,C12)),np.hstack((C21,C22))))

    return C

In [3]:
#테스트 코드
A=np.array([[0,1],[2,3]])
B=np.array([[4,5],[0,2]])
C=strassen(A,B)
print(A)
print(B)
print(C)

[[0 1]
 [2 3]]
[[4 5]
 [0 2]]
[[ 0  2]
 [ 8 16]]
